

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SITE_URL=http://localhost:3000
      - NEXT_PUBLIC_SUPABASE_URL=http://supabase-kong:8000
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
      - NEXT_PUBLIC_REQUIRE_EMAIL_CONFIRMATION=true
      - EMAIL_SENDER=test@makerkit.dev
      - EMAIL_PORT=54325
      - EMAIL_HOST=supabase-inbucket
      - EMAIL_TLS=false
      - EMAIL_USER=user
      - EMAIL_PASSWORD=password
      - NEXT_PUBLIC_ENABLE_ACCOUNT_DELETION=true
      - NEXT_PUBLIC_ENABLE_ORGANIZATION_DELETION=true
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    stdin_open: true
    tty: true

